//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MST_POS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPos
    {
        public int ID { get; set; }
        public int NoKodePos { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string Jenis { get; set; }
        public string Kabupaten { get; set; }
        public string Propinsi { get; set; }
    }
}
